name: Unit testing on ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install lacmus
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow==2.3.0
        pip install keras==2.4.3
        pip install opencv-python
        pip install --upgrade setuptools
        pip install .
        python setup.py build_ext --inplace
        pip install pytest
        pip install pycocotools
        git clone https://github.com/lacmus-foundation/lacmus-test-data.git tests/test-data
    - name: Run tests
      run: pytest tests